### ISSUE TITLE
能否提供在windows server 下部署的指导

### ISSUE THREAD

**Issue by ChiaoZenYee** [SmartforXiaoYuan/QuartzCore.Blazor#3]
@SmartforXiaoYuan 求windows server下部署的指导

**Comment by KnightYyj** [comment]
是IIS部署？(iis的话直接发布运行，若不需要mongo把mongo service注释掉。)还是说windows服务的任务？

**Comment by ChiaoZenYee** [comment]
> 
> 
> 是IIS部署？(iis的话直接发布运行，若不需要mongo把mongo service注释掉。)还是说windows服务的任务？

我是指在IIS下部署：） 如果在IIS下部署您这个项目，是不是也有 Quartz 的进程被杀掉的问题 ？

**Comment by KnightYyj** [comment]
IIS下需要设置下不需要自动回收，你这个情况也也遇到过，我后来直接部署的docker。我用iis测试下如何设置

**Comment by ChiaoZenYee** [comment]
项目整体跑起来后，首页底部出现 “An unhandled error has occurred. Reload”。我在浏览器控制台里看到如下报错信息：
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[QuartzCore.Blazor.Shared.MessageModel`1[[QuartzCore.Blazor.Shared.DashDto, QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[QuartzCore.Blazor.Shared.MessageModel`1[[QuartzCore.Blazor.Shared.DashDto, QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[MessageModel`1](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[MessageModel`1](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.<ReadAsync>d__20`1[[QuartzCore.Blazor.Shared.MessageModel`1[[QuartzCore.Blazor.Shared.DashDto, QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__3`1[[QuartzCore.Blazor.Shared.MessageModel`1[[QuartzCore.Blazor.Shared.DashDto, QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__9`1[[QuartzCore.Blazor.Shared.MessageModel`1[[QuartzCore.Blazor.Shared.DashDto, QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], QuartzCore.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at QuartzCore.Blazor.Client.Pages.Index.OnQuery()
   at QuartzCore.Blazor.Client.Pages.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by KnightYyj** [comment]
这个我有修复一下，应该是任务列表没数据的时候产生的异常
